
export const SEE_ALL = 'see_all'
export const SEE_ONE = 'see_one'
export const ADD_TO_CART = 'add_to_cart'
export const REMOVE_FROM_CART = 'remove_from_cart'
export const CALC_TOTAL = 'calc_total'
export const INCREASE_QUANT = 'increase_quant'
export const DECREASE_QUANT = 'decrease_quant'
export const SET_USER = 'set_user'
export const LOG_USER = 'log_user'
export const LOG_OUT = 'log_out'
export const FROM_INPUT = 'from_input'
export const SET_ITEMS = 'set_items'
export const SET_MESSAGE = 'set_message'
export const SET_ORDERS = 'set_orders'
export const CLEAR_CART = 'clear_cart'